name: merchant_pos_app
description: Agri-Yield Merchant POS App
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dio: ^5.3.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  intl: ^0.20.2
  mobile_scanner: ^3.5.6
  qr_flutter: ^4.1.0
  audioplayers: ^5.2.1
  fl_chart: ^0.66.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
    - assets/sounds/success.mp3
    - assets/sounds/error.mp3